export const ICONS = {
  bookmark: require("../assets/icons/bookmark.png"),
  bookmarkFilled: require("../assets/icons/bookmark-filled.png"),
  home: require("../assets/icons/home.png"),
  search: require("../assets/icons/search.png"),
  settings: require("../assets/icons/settings.png"),
  back: require("../assets/icons/back.png"),
  rightArrow: require("../assets/icons/right-arrow.png"),
  anchovy: require("../assets/icons/anchovy.png"),
  cheese: require("../assets/icons/cheese.png"),
  chicken: require("../assets/icons/chicken.png"),
  chilli: require("../assets/icons/chilli.png"),
  coriander: require("../assets/icons/coriander.png"),
  egg: require("../assets/icons/egg.png"),
  garlic: require("../assets/icons/garlic.png"),
  lemongrass: require("../assets/icons/lemongrass.png"),
  oil: require("../assets/icons/oil.png"),
  onion: require("../assets/icons/onion.png"),
  pasta: require("../assets/icons/pasta.png"),
  pepper: require("../assets/icons/pepper.png"),
  potato: require("../assets/icons/potato.png"),
  rice: require("../assets/icons/rice.png"),
  shallot: require("../assets/icons/shallot.png"),
  salt: require("../assets/icons/salt.png"),
  sugar: require("../assets/icons/sugar.png"),
  shrimp: require("../assets/icons/shrimp.png"),
  tomato: require("../assets/icons/tomato.png"),
};
